### PR TITLE
Fix inputs for directory and poll, add elevation tiles

### PR DESCRIPTION
**Pull request by henryfok**
Fixes:
Input text and elevation tiles (Credits to #31)
image

Member list status filter
image

My Data buttons
image

### CODE REVIEW

**Comment by ankar84** [comment]
All good except poll dropdown list
image

**Comment by pbaity** [comment]
@henryfok Looks like there are still some issues with poll app and some conflicts to be resolved.

image

**Comment by pbaity** [comment]
@henryfok Can you give me an update on what this PR accomplishes now? Since Rocket.Chat has been updated several times since it was opened the title and original description is no longer accurate.

**Comment by henryfok** [comment]
I'm going to close this PR, as the changes no longer apply for the recent versions of RC.

**Pull request closed without merging**
