### PR TITLE
3.12.x - Quotes, Pinned messages, Sidebar in panels

### LINKED ISSUE #121: Color of cited messages
**Describe the bug**
The color of cited message is not rendered in dark mode

**To Reproduce**
1. Cite a message
2. switch to dark mode

**Expected behavior**

**Screenshots**
grafik

**Desktop (please complete the following information):**
 - OS: Win
 - Browser Firefox
 - Version 85

### LINKED ISSUE #122: Card is not rendered in dark mode
**Describe the bug**
The user card is not rendered in dark mode, icons not visible

**To Reproduce**
1. click on a users avatar
2. see card

**Expected behavior**
visible icons, dark colos

**Screenshots**
grafik

**Desktop (please complete the following information):**
 - OS: Win
 - Browser FF
 - Version 85

### PR DESCRIPTION
**Pull request by TBG-FR**
- Fixes #121
- Fixes kinda the same issue, but for pinned messages announcement
- Fixes the background-color of panels' sidebars (css class has been changed)

Edit: Now also fixes #122 

Enjoy ;)

### CODE REVIEW

**Comment by pbaity** [comment]
Thanks @TBG-FR , I just merged #123 which introduced another conflict here. If that fix works in 3.12.x for you, we can keep it, otherwise let me know.

**Comment by TBG-FR** [comment]
I checked, and #123 and my commits are separate things, but git have seen them as conflicts anyway, that should be good now ;)

**Comment by fdellwing** [comment]
The conflict is that `body.dark-mode .rcx-attachment__content .rcx-css-16qhlle` is a dead rule, it was replaced in #123 with `body.dark-mode .rcx-message-attachment .rcx-attachment__content .rcx-box--full` and the `!important` was removed as it was no longer necessary.

So maybe just move my new rule to the location you commented with `/* Attachements content */`.

**Comment by TBG-FR** [comment]
> 
> 
> The conflict is that `body.dark-mode .rcx-attachment__content .rcx-css-16qhlle` is a dead rule, it was replaced in #123 with `body.dark-mode .rcx-message-attachment .rcx-attachment__content .rcx-box--full` and the `!important` was removed as it was no longer necessary.
> 
> So maybe just move my new rule to the location you commented with `/* Attachements content */`.
> 
> P.S. We should maybe wait with this until 3.12.1 drops, 3.12.0 contains a serious bug with Jitsi and will hopefully be patched really quickly. Afterwards the generated classes would be needed to be replaced again.

I'm sorry I thought I placed your new rule here, I should open my eyes more ahah
I'll do that, that was the point of my pull of master but looks like I failed ahah

Yeah I'm also following the Jitsi bug... I'll update the code anyway and we'll see !

**Comment by TBG-FR** [comment]
Looks like I did it right in fact, your code is under `/* Attachements */` and the code above it is related to quotes ;)

**Comment by fdellwing** [comment]
Nah I think you are mixing things up. Currently there are two things related to attachements in your PR.

Line 188ff contains the new rule for text attachements
Line 203ff contains the rule that #123 removed

**Comment by TBG-FR** [comment]
Yeah, it's really time to close the computer, didn't see that the old rule was still there 😅 
I'll remove the rule line 203 then !

**Comment by fdellwing** [comment]
Thanks, I'll take a look at your new rules at work tomorrow.

**Comment by fdellwing** [comment]
I'm not completely happy with the PR.

I would like to add the following rule for blockquotes:

```
body.dark-mode blockquote.rcx-attachment__details .rcx-box--full {
  color: var(--primary-font-color);
}
```

Also you would be very nice if you change `--color-white` to `--primary-font-color` in line 190.

**Comment by TBG-FR** [comment]
I'll modify the rule line 190, no issue.

However, I'd say we should use `color: var(--secondary-font-color);` for quotes, as it's what is done in the regular RocketChat theme : quoted content isn't as "light" as normal content (they're using the rule `color: var(--rcx-color-foreground-info, #6c727a) !important;`)

image

I'll put that, but if you don't agree, let me know @fdellwing !

**Comment by fdellwing** [comment]
In that case just ignore my request and use the color RC intends to. I'll create a fork and change it there so that is looks good for us.

**Comment by TBG-FR** [comment]
> 
> 
> In that case just ignore my request and use the color RC intends to. I'll create a fork and change it there so that is looks good for us.
> 
> We already overwrite the `--color-darkest` value to a much lighter grey, so I guess thats a good point to fork.

Alright ! Still, sorry for the inconvenience

@pbaity I think we're good on this one ;)

**Comment by fdellwing** [comment]
Did you check the PR against the new 3.12.1 published today?

**Comment by TBG-FR** [comment]
I'm checking it as we speak, everything seems to work well : quotes, modals, sidebars, ...

**Comment by TBG-FR** [comment]
@pbaity I'm ready ;)

**Comment by pbaity** [comment]
Thanks to you and @fdellwing both for the great work on this PR!

**Review by pbaity — APPROVED** [review]

**Pull request merged**
