### PR TITLE
[Fix] Reactions modal background color

### PR DESCRIPTION
**Pull request by ankar84**
With this fix you get solid Reactions modal view in Dark Mode
image
closes https://github.com/pbaity/rocketchat-dark-mode/issues/143

### CODE REVIEW

**Comment by ankar84** [comment]
Button background need to be redone, because it broke other modals like call start
image
Or another way is to set all modals background to same color.

**Comment by ankar84** [comment]
I guess there is now easy fix for that.
I dud try to set whole background color to match both colors of button and list with

```
body.dark-mode .rc-modal-- {
	background-color: var(--color-dark-80);
}
```

And it looks pretty well
image

But other modals are broken again
image

I don't know how to fix that for now

**Comment by pbaity** [comment]
@ankar84 Did you figure out a fix for this that doesn't break anything elsewhere?

**Comment by ankar84** [comment]
> @ankar84 Did you figure out a fix for this that doesn't break anything elsewhere?

Nope, unfortunately

**Comment by pbaity** [comment]
Closing since the issue seems to be resolved anyway as of 3.18.1

**Pull request closed without merging**
