### PR TITLE
Initial changes for working with 3.8.0 (NOT backwards-compatible!)

### PR DESCRIPTION
**Pull request by bkraul**
Minimal initial changes to support dark mode in 3.8.0.

### CODE REVIEW

**Comment by bkraul** [comment]
Hopefully this addresses #80 .

**Comment by pbaity** [comment]
@bkraul Let me know when this is ready to merge. Only concern I have so far is that I see generated class names in these changes (like `rcx-@ue04p` on the toggle button) which, if I understand correctly, are subject to change between versions.

**Comment by bkraul** [comment]
It should be ready to merge into 3.8.0 branch. As mentioned, it has some quirks but it works for the most part. It seems those generated classes are pretty stable, as I have been through several builds of 3.8.0-develop and they have not changed. I would figure they would only change if they revamp the classes again, in which case we would have to address anyway.

Really right now, it would be great to make the distinction between the sidebar and main-content theming and to bring back the dark admin sidebar. But that seems quite laborious.

**Comment by pbaity** [comment]
I'm merging this now so others using 3.8.0-develop can get these fixes. I still don't have a 3.8.0-develop instance running for development and testing but I hope to soon so I can help out with getting the sidebar and other quirks sorted out.

**Pull request merged**
