### PR TITLE
Changes for 3.11-develop

### PR DESCRIPTION
**Pull request by bkraul**
Minor fixes:
- Proper dark mode button icon size.
- Minor issues on chat window.

### CODE REVIEW

**Comment by pbaity** [comment]
@bkraul I'm running this in my instance now to test it, but a few questions - is this for 3.8.0 or a newer version? On 3.9.3 (my daily running instance) the font-size of the icons is set to `1.25rem !important` by the default stylesheets, and this overrides the `1em !important` style you added:

image
image

If I disable this other rule so yours takes effect:

image

And I also see no difference as I toggle the rule for the height of `1rem` either.

As for the rule to style `.main-content .rcx-box` with a `--color-darkest` background, I didn't realize it but we already have this rule on [line 746](https://github.com/pbaity/rocketchat-dark-mode/blob/master/dark-mode.css#L746), which is why I wasn't noticing a difference. We can remove the rule on line 600 for this, unless you're seeing an issue that your change addresses.

**Comment by bkraul** [comment]
@pbaity, yes, I am running a much newer version, 3.11-develop. The issue I am running into is that the icon shows up as much smaller than the rest of the icons, but that gets corrected with the:
```css
font-size: 1rem !important;
```
line.

**Comment by bkraul** [comment]
Also, please be aware that the changes you mention also seem to be causing some issues, such as #107 .

**Comment by pbaity** [comment]
@bkraul Sorry for the delay - I just created a 3.9.1 branch so the existing code can continue to (mostly) work for older versions. Now you can remove code that causes issues for your version. Let me know when it's ready for review, and in the meantime I'll get a test instance set up.

Rocket.Chat is updating faster than I can keep up with in my spare time, but I'll try to keep the master branch up to date with the most recent version (including `-develop`) available.

**Comment by TBG-FR** [comment]
I created a pull request with modifications for 3.11, but I didn't touched the icon size, so I think our two PR will fit together 😄

**Review by pbaity — APPROVED** [review]

**Comment by pbaity** [comment]
Sorry for the terrible delay on this, I've been slammed with work! Hope that doesn't stop more PRs from coming as we all try to keep up with the rate of change in Rocket.Chat.

**Pull request merged**
