### PR TITLE
add dark background for elevation tiles

### PR DESCRIPTION
**Pull request by AntouanK**
Adding a small rule for the elevation tiles.
To test it, search for a channel name that has no results.
The text "No data found" was on white background initially.

Screenshot from 2020-04-27 08-43-11

### CODE REVIEW

**Comment by pbaity** [comment]
@AntouanK what version of RocketChat are you using? This doesn't happen for me:
image
I trust your changes are good but I'd love to see them for myself 🙂

**Comment by AntouanK** [comment]
Yeah, of course.

I'm using 3.1.1
and I just used your theme.

Thanks for your work btw :+1:

**Comment by pbaity** [comment]
@AntouanK Looks like I'm at 2.4.11 because we're using the snap install, and the `latest/stable` channel is set to 2.x. I and the other administrator on our instance are going to be working on upgrading (which should be easy, just want to be careful) so we can test these and the other 3.x issues and PRs that will surely start showing up.

Just wanted to let you know why there's a delay, but shouldn't be a long one.

**Comment by pbaity** [comment]
@AntouanK Finally upgraded and tested, and it looks great! Sorry for the delay over the small fix 😞 Merging now.

**Comment by AntouanK** [comment]
Thank you @pbaity 
No worries.

**Pull request merged**
