### PR TITLE
Fix Rocket Chat scrollbar thumb invisible

### LINKED ISSUE #74: Scrollbar thumb almost invisible in Rocket Chat
**Describe the bug**
scrollbar-thumb almost invisible.
It's not a dark mode issue, it's Rocket Chat itself issue
I want to fix that in dark mode CSS

**To Reproduce**
1. Go to sidebar
2. Try to scroll up and down
3. Scrollbar thumb almost invisible

**Expected behavior**
Visible scrollbar thumb

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 85

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 9 SE
 - OS: Android 10
 - Browser Chrome
 - Version 85

**Additional context**
I have a fix for that

### PR DESCRIPTION
**Pull request by ankar84**
closes #74
Set color to thump
image

### CODE REVIEW

**Comment by pbaity** [comment]
@ankar84 There is a variable for this that you can set under the `Overridden Rocket.Chat Variables` section of the stylesheet, like so:
```css
--custom-scrollbar-color: background-color: rgba(255, 255, 255, 0.15);
```
There's a rule that applies this variable to the scrollbar thumb in the main RocketChat styles. Test it out and see if that works for you.

**Comment by ankar84** [comment]
> Test it out and see if that works for you.

Yes, I think it's work!
image
I commented code from this RP and added this
```
	/* scrollbar */
	--custom-scrollbar-color: background-color: rgba(255, 255, 255, 0.15);
}
```
to **Overridden Rocket.Chat Variables** section.
Looks same.

**Comment by pbaity** [comment]
Great, if you're satisfied with that change, update the PR and I can approve and merge.

**Comment by ankar84** [comment]
> Great, if you're satisfied with that change, update the PR and I can approve and merge.

done

**Comment by ankar84** [comment]
> Test it out and see if that works for you.

Wait a minute. @pbaity 
I think now it fixes scrollbar thumb only for dark mode and not for normal mode
Dark Mode
image
Normal Mode
image

**Comment by pbaity** [comment]
@ankar84 Ah, I see. You can define the variable under `:root` and the top of the stylesheet.

**Comment by ankar84** [comment]
> You can define the variable under `:root` and the top of the stylesheet.

Done.
So, strange - it's still works only for dark mode and do not work in normal mode.
I did CTRL+F5 in browser - but still same.

**Comment by ankar84** [comment]
@pbaity I think I found a better place for that fix.
In already existed `/**************Scrollbars******************/` section
In most recent commit I just deleted `body.dark-mode ` part from 
```
body.dark-mode *::-webkit-scrollbar-thumb {
	background-color: rgba(255, 255, 255, 0.15);
}
```

And for me it looks perfect in both dark and light mode

**Comment by pbaity** [comment]
After testing a few different options I noticed something...I reset my stylesheet to the code in the master branch here. It looks like the scrollbar wasn't even broken for me:
image
If you use code in the master branch, is the scrollbar thumb still invisible? Because we've got [rules that should be styling it already](https://github.com/pbaity/rocketchat-dark-mode/blob/master/dark-mode.css#L661-L671).

Another thought, we probably only want to worry about fixing the dark mode scrollbar in this repository. If we add rules to change things in light mode in this codebase, they may become unnecessary or conflict with other rules further down the road, especially if the Rocket.Chat bug gets fixed or other things change. So if your scrollbar is still invisible, let's just focus on fixing it for dark mode. You can keep rules to fix light mode in your local copy though (I will be keeping your fix in mine).

Let me know if you really disagree or your general thoughts.

**Comment by ankar84** [comment]
> Another thought, we probably only want to worry about fixing the dark mode scrollbar in this repository. If we add rules to change things in light mode in this codebase, they may become unnecessary or conflict with other rules further down the road, especially if the Rocket.Chat bug gets fixed or other things change. So if your scrollbar is still invisible, let's just focus on fixing it for dark mode. You can keep rules to fix light mode in your local copy though (I will be keeping your fix in mine).

Totally agree with you, but it worth to try.
I will fix it for my deployment locally.

**Comment by pbaity** [comment]
Yeah, it hurts me to not try to fix the issue, but I want to keep the repo clean to it's easier for us all to maintain. Is the scrollbar in dark mode still invisible for you? With code from the master branch I had no issues with the scroll bar.

**Comment by ankar84** [comment]
> Is the scrollbar in dark mode still invisible for you?

No, scrollbar thumb was always visible in Dark mode.
Whole problem only in normal Rocket Chat mode.

**Comment by pbaity** [comment]
@ankar84 Ah, ok. I will close the issue and PR then. Thank you for bringing it up anyway.

**Pull request closed without merging**
