### PR TITLE
Modifications for 4.3.0

### PR DESCRIPTION
**Pull request by TBG-FR**
Some CSS modifications to fix things that have been broken by RC 4.3.0 😉 
Thanks to @ae5960e8-a6fc-491f-b252-898ecf59af95 for pointing some of them in #161

- Left sidebar menus (Account, Display) colors (background, text, hover)
- Message option menu (three dots) colors (hover)
- Modals
  - Close button (cross icon on top right) color (hover)
  - Cancel button (when `.rcx-button--ghost` class is missing) color (text) (-> #144 )
- 2FA codes display box in Account menu (background)
- ...

Don't hesitate to tell me if you find something wrong or not working as expected !

### CODE REVIEW

**Review by ae5960e8-a6fc-491f-b252-898ecf59af95 — APPROVED** [review]

**Review by ae5960e8-a6fc-491f-b252-898ecf59af95 — DISMISSED** [review]
Thanks, my team and I whom use Rocket.Chat appreciate it.

**Comment by TBG-FR** [comment]
My pleasure ! 😄

I think we'll also have to clean the CSS file because a lot of css classes are gone with 4.3.0, but I think it's better to do it in another PR, after having a fully working dark theme

**Review by ae5960e8-a6fc-491f-b252-898ecf59af95 — APPROVED** [review]

**Comment by pbaity** [comment]
@TBG-FR This is looking great so far, thanks so much for these fixes! Just tag me on here when you're ready for a final review and merge.

**Comment by TBG-FR** [comment]
@pbaity I think we're good, you can merge and I'll open another PR if I find anything else ;)

**Review by pbaity — APPROVED** [review]

**Pull request merged**
