### PR TITLE
3.11.x improvements : Admin/Account panels, tables and minor fixes

### PR DESCRIPTION
**Pull request by TBG-FR**
As said in the title, I highly improved Admin/Account panels look in Dark Theme (sidebars, backgrounds, etc), and did some other minor modifications, especially on tables.

Enjoy ;)

### CODE REVIEW

**Comment by brunobertoldi** [comment]
Admin and Account look great!

**Comment by fdellwing** [comment]
Admin looks really good 👍

**Comment by pbaity** [comment]
Looks great! Merging.

**Review by pbaity — APPROVED** [review]

**Comment by pbaity** [comment]
I've mentioned this several times elsewhere, but just to be consistent, a warning that rules that apply to class names like `.rcx-css-dlop43` (generated classes) are highly likely to break at the next release (and may already not work for anyone using a different version). Of course we still want the short-term fix, but if there's ever a way to target the same elements via more stable parent or sibling classes, that would be more future-proof.

**Comment by fdellwing** [comment]
The problem is, that most classes are very general and since RC is full of very specific rules that target generated classes it is hard to get even more specific rules without using the generated classes.

**Comment by pbaity** [comment]
If there was an emoji on GitHub for "bullseye" I'd react with that instead. I hope in the future that Rocket.Chat will make custom styling easier - it's gotten more difficult over time, not better. Or, of course, they're welcome to [introduce a native dark mode anytime now](https://github.com/pbaity/rocketchat-dark-mode/issues/27#issuecomment-625368663) - nothing would make me happier than to retire this repo and declare mission accomplished.

**Pull request merged**
